export const projects = [
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/mates.png",
  //   name: "Donors",
  //   ext: "jsx",
  //   lang: "js",
  //   git: "https://youtu.be/Zm4ptkIXlTA",
  //   live: "http://mw.mait.ac.in/",
  // },
  {
    img: "https://user-images.githubusercontent.com/74147463/138558412-e8b7fa8b-0577-40bf-8d04-d6e6cc4a4b31.png",
    name: "Moogle",
    ext: "vercel.app",
    lang: "ssr",
    git: "https://github.com/VanshajPoonia/moogle",
    live: "https://moogle.vercel.app/",
  },
  {
    img: "https://user-images.githubusercontent.com/74147463/138558499-e9bdf137-ab10-44b6-9842-6bf772f2c87f.png",
    name: "Vanshaj Poonia",
    ext: "vercel.app",
    lang: "ssr",
    git: "https://github.com/VanshajPoonia/vanshajpoonia.vercel.app",
    live: "https://vanshajpoonia.vercel.app/",
  },

  {
    img: "https://user-images.githubusercontent.com/74147463/138558703-30e5f099-18c9-4221-93eb-464bdbb2aa9b.png",
    name: "Physicsviz",
    ext: "vercel.app",
    lang: "ssr",
    git: "https://github.com/VanshajPoonia/physicsviz",
    live: "https://physicsviz.vercel.app/",
  },
  {
    img: "https://user-images.githubusercontent.com/74147463/138558990-6f8db9ae-4878-48e9-a329-6e8fbf4ee8fa.png",
    name: "Facebook clone",
    ext: "web.app",
    lang: "react",
    git: "https://github.com/VanshajPoonia/hypnover",
    live: "https://facebook-react-e146d.web.app/",
  },

  {
    img: "https://user-images.githubusercontent.com/74147463/138558144-d1392fe7-88f6-4f31-bf38-2daf2020c888.png",
    name: "Hammr",
    ext: "pages.dev",
    lang: "html n css",
    git: "https://github.com/VanshajPoonia/hammr",
    live: "https://hammr.org/",
  },
  {
    img: "https://user-images.githubusercontent.com/74147463/138559132-3ba64b6e-a275-4ad6-ae3d-a804ffafa3a3.png",
    name: "Cryptant",
    ext: "",
    lang: "hybrid",
    git: "https://github.com/VanshajPoonia/cryptant",
    live: "https://github.com/VanshajPoonia/cryptant",
  },
  {
    img: "https://user-images.githubusercontent.com/74147463/138559454-246c1258-54ad-4cbb-b50c-9e2279d16ad7.jpeg",
    name: "Friday",
    ext: "py",
    lang: "py",
    git: "https://github.com/VanshajPoonia/friday",
    live: "https://github.com/VanshajPoonia/friday",
  },

  {
    img: "https://user-images.githubusercontent.com/74147463/138559612-fd799884-b13f-4a51-9c94-1149f9c9dea5.png",
    name: "Snapchat clone",
    ext: "web.app",
    lang: "react",
    git: "https://github.com/VanshajPoonia/slapchat",
    live: "https://snapchat-12dbe.web.app",
  },
  {
    img: "https://user-images.githubusercontent.com/74147463/138559695-e2c14fe4-8e48-4014-b5bb-fe34b3ecdd61.png",
    name: "Hypnover",
    ext: "pages.dev",
    lang: "html n css",
    git: "https://github.com/VanshajPoonia/hypnover",
    live: "https://hypnover.pages.dev/",
  },
  {
    img: "https://user-images.githubusercontent.com/74147463/138559776-2d01a85a-4eba-4969-9d5c-ac62a30c262f.png",
    name: "Bhhatsapp",
    ext: "vercel.app",
    lang: "ssr",
    git: "https://github.com/VanshajPoonia/bhhatsapp",
    live: "https://bhhatsapp.vercel.app/",
  },
  {
    img: "https://user-images.githubusercontent.com/74147463/138559821-24be00cb-e9c0-4589-a88b-d55e8c4c41ae.png",
    name: "Moogle maps",
    ext: "pages.dev",
    lang: "html n css",
    git: "https://github.com/VanshajPoonia/moogle-maps",
    live: "https://mooglemaps.pages.dev/",
  },
  {
    img: "https://user-images.githubusercontent.com/74147463/138560043-d8d74c20-1b8c-4f1e-8cf4-41de87cab04d.png",
    name: "Moogle Drive",
    ext: "web.app",
    lang: "react",
    git: "https://github.com/VanshajPoonia/moogle-drive",
    live: "https://ggl-drive-1029.web.app/",
  },
  {
    img: "https://user-images.githubusercontent.com/74147463/138560125-a554c509-0696-4d39-93b2-996b186b2ebb.png",
    name: "Hypnosys",
    ext: "business.site",
    lang: "ssr",
    live: "https://hypnosys.business.site/",
  },

  {
    img: "https://user-images.githubusercontent.com/74147463/138560118-a8b7a159-fd5f-48be-83a9-59c97c37d5e6.png",
    name: "Mewtube",
    ext: "web.app",
    lang: "react",
    git: "https://github.com/VanshajPoonia/mewtube",
    live: "https://mewtube-op.web.app/",
  },

  {
    img: "https://res.cloudinary.com/practicaldev/image/fetch/s--a5kaccIG--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://thumbs.gfycat.com/FreshAnyHanumanmonkey-size_restricted.gif",
    name: "Jarvis",
    ext: "py",
    lang: "py",
    git: "https://github.com/VanshajPoonia/jarvis",
    live: "https://github.com/VanshajPoonia/jarvis",
  },

  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/blog.jpg",
  //   name: "Django Blog",
  //   ext: "py",
  //   lang: "py",
  //   git: "https://github.com/smrnjeet222/Django_Blog",
  //   live: "https://smrnjeetblogs.herokuapp.com/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/Python_Apps/master/Rock-Paper-Scissors/demo.jpg",
  //   name: "Multiplayer R.P.S",
  //   ext: "py",
  //   lang: "py,games",
  //   git: "https://github.com/smrnjeet222/Python_Apps/tree/master/Rock-Paper-Scissors",
  //   live: "https://github.com/smrnjeet222/Python_Apps/tree/master/Rock-Paper-Scissors",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/Python_Apps/master/Snake/Extras/play.png",
  //   name: "Snake Game",
  //   ext: "py",
  //   lang: "py,games",
  //   git: "https://github.com/smrnjeet222/Python_Apps/tree/master/Snake",
  //   live: "https://github.com/smrnjeet222/Python_Apps/tree/master/Snake",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/portfolio.png",
  //   name: "Old Portfolio",
  //   ext: "js",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/Portfolio",
  //   live: "https://smrnjeet222.github.io/Portfolio/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/surepass/bgvAll.png",
  //   name: "Surepass",
  //   ext: "jsx",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/Surepass/blob/main/README.md",
  //   live: "https://github.com/smrnjeet222/Surepass/blob/main/README.md",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/Python_Apps/master/SudokuSolver/2.png",
  //   name: "Sudoku Solver",
  //   ext: "py",
  //   lang: "py,games",
  //   git: "https://github.com/smrnjeet222/Python_Apps/tree/master/SudokuSolver",
  //   live: "https://github.com/smrnjeet222/Python_Apps/tree/master/SudokuSolver",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/newslaundry.png",
  //   name: "Newslaundry",
  //   ext: "jsx",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/newslaundry",
  //   live: "https://smrnjeet222.github.io/newslaundry/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/recipe.jpg",
  //   name: "Recipe App",
  //   ext: "jsx",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/recipe-app",
  //   live: "https://smrnjeet222.github.io/recipe-app/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/bubblesort.png",
  //   name: "Visualisations",
  //   ext: "js",
  //   lang: "js",
  //   git: "https://editor.p5js.org/smrnjeet222/collections/fvtHa48dt",
  //   live: "https://editor.p5js.org/smrnjeet222/sketches/T0o5woDT5",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/covid.png",
  //   name: "Python Apps",
  //   ext: "py",
  //   lang: "py",
  //   git: "https://github.com/smrnjeet222/Python_Apps",
  //   live: "https://github.com/smrnjeet222/Python_Apps",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/background.gif",
  //   name: "DumpBox",
  //   ext: "jsx",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/DropBox-Clone",
  //   live: "https://github.com/smrnjeet222/DropBox-Clone",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/pg.png",
  //   name: "Pico-Gram",
  //   ext: "jsx",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/PicoGram",
  //   live: "https://smrnjeet-picogram.web.app/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/BLENDER/master/Abstract_Design/Abstract.png",
  //   name: "Blender",
  //   ext: "models",
  //   lang: "games",
  //   git: "https://github.com/smrnjeet222/BLENDER",
  //   live: "https://smrnjeet222.github.io/BLENDER/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/worldRanks.png",
  //   name: "WorldRanks",
  //   ext: "tsx",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/WorldRanks",
  //   live: "https://world-ranks-smrnjeet222.vercel.app/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/Unity_Gamedevelopment/master/MYGAME.png",
  //   name: "Unity Games",
  //   ext: "c#",
  //   lang: "games",
  //   git: "https://github.com/smrnjeet222/Unity_Gamedevelopment",
  //   live: "https://smrnjeet-22.itch.io/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/background.gif",
  //   name: "NoJs-TicTacToe",
  //   ext: "css",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/noJs-TicTacToe",
  //   live: "https://codepen.io/smrnjeet222/full/gOLjOXM",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/Automail.png",
  //   name: "AutoMail",
  //   ext: "py",
  //   lang: "py",
  //   git: "https://github.com/smrnjeet222/AutoMail",
  //   live: "https://github.com/smrnjeet222/AutoMail",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/Unity_Gamedevelopment/master/FreakyFrog/best.png",
  //   name: "Freaky Frog",
  //   ext: "c#",
  //   lang: "games",
  //   git: "https://github.com/smrnjeet222/Unity_Gamedevelopment",
  //   live: "https://smrnjeet-22.itch.io/freaky-frog",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/Astar.png",
  //   name: "A*Pathfinding",
  //   ext: "py",
  //   lang: "py",
  //   git: "https://github.com/smrnjeet222/Python_Apps/tree/master/A-star",
  //   live: "https://repl.it/@smrnjeet222/Astar#main.py",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/Python_Apps/master/Space-invaders/Sc.jpg",
  //   name: "Space-invaders",
  //   ext: "py",
  //   lang: "py,games",
  //   git: "https://github.com/smrnjeet222/Python_Apps/tree/master/Space-invaders",
  //   live: "https://github.com/smrnjeet222/Python_Apps/tree/master/Space-invaders",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/Rc.png",
  //   name: "Ray Casting",
  //   ext: "js",
  //   lang: "js",
  //   git: "https://editor.p5js.org/smrnjeet222/collections/fvtHa48dt",
  //   live: "https://editor.p5js.org/smrnjeet222/sketches/j06TXs4ZF",
  // },
];
